### ISSUE TITLE
There is a wrong 

### ISSUE THREAD

**Issue by Mostaphadartagnan** [NAGA-HiTAM/blumcok#1]
In the line 282
Its like that 
`self.log(f"{hijau}green}Farming started")`
That wrong 
It should be like this 
`self.log(f"{hijau}green Farming started")`

And secend problem, that script can't play the gime 😞
![Uploading Screenshot_2024-10-12-15-34-16-82_84d3000e3f4017145260f7618db1d683.jpg…]()

**Comment by NAGA-HiTAM** [comment]
Git pull

**Comment by Mostaphadartagnan** [comment]
![Screenshot_2024-10-12-15-51-06-82_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/user-attachments/assets/28671555-9242-4623-a377-d92c6ad686d8)

Same bro. The game didn't played

**Comment by NAGA-HiTAM** [comment]
Wait for update payload
